{{- if .Values.gitea.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
  name: {{ .Release.Name }}-ofc-gitea-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "osm-for-cities.name" . }}
    component: ofc-gitea-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  type: {{ .Values.serviceType }}
  selector:
    app:  {{ .Release.Name }}-ofc-gitea-app
{{- end }}
